### ISSUE TITLE
potential memory leak & performance drop

### ISSUE THREAD

**Issue by a3706** [rosebudmods/skin-overrides#10]
### minecraft version

Tricky Trials (1.21.1)

### mod version

2.2.2

### mod loader

fabric

### what went wrong?

Setting a skin override appears to cause some sort of memory leak. Pausing the game did not stop memory usage from increasing, removing the override or exiting the world causes memory usage to stop increasing, but does not go back down.
I could only get this behavior to occur with version 2.2.2

Having an override set for yourself also seems to cause a large fps drop

No override
![before1](https://github.com/user-attachments/assets/be0ec0c6-88a7-41cf-9ae3-52ba29512ae6)
Override set
![after1](https://github.com/user-attachments/assets/a96cec66-7a74-4745-ab06-d41ff4238855)

current mods folder:
![2024-12-16_21-03](https://github.com/user-attachments/assets/a410bdac-127e-40c8-b788-47365ed5a053)
loader version 0.16.9

before setting any overrides / opening menu
![before](https://github.com/user-attachments/assets/15bb5ea6-341e-48eb-8bb3-5fd44dad750a)
a few minutes after setting an override
![after](https://github.com/user-attachments/assets/4b136495-5b03-40b7-a8c0-fdf4e37bc827)

### log file
(not much here)
https://mclo.gs/IrA5caT

**Comment by orifu** [comment]
i *think* this issue is fixed in the 2.2.3 beta (number of `DynamicTexture`s and `NativeImage`s didn't seem to balloon like in 2.2.2) but i was seeing some other objects still have high counts that may or may not be related to the mod (i'm not entirely sure).

as for the performance issue, i have confirmed it's a separate issue and will work on fixing that later

**Comment by orifu** [comment]
performance issues should be fixed in 1144aa8e5349fb376dcf644cad8d284f97cf74c2

**Comment by orifu** [comment]
i ran minecraft for an hour and didn't see anything out of the ordinary so i think this is all fixed now

**Comment by a3706** [comment]
could not get either issue to occur with recent change, appears to be fixed

**Comment by orifu** [comment]
thanks for testing!
