### ISSUE TITLE
Suggestion: Networking for 1.20.1?

### ISSUE THREAD

**Issue by avilonlegends** [rosebudmods/skin-overrides#5]
### description

Hi there, your mod look really great!

Quick question, would it perhaps be possible to make the networking function for servers available to version 1.20.1 as well? I saw in your wiki that this option is available only for versions 1.20.6 upwards.

In any case, thank you!

**Comment by orifu** [comment]
ill look into it!

**Comment by orifu** [comment]
added in 2.2.2! https://modrinth.com/mod/skin-overrides/version/2.2.2+1.20.1
