### ISSUE TITLE
Interface is not transparent

### ISSUE THREAD

**Issue by avilonlegends** [rosebudmods/skin-overrides#7]
### minecraft version

1.20.1

### mod version

2.2.2

### mod loader

fabric

### what went wrong?

Hi again!

Thank you so much for the update!
Unfortunately, I've stumbled upon an issue in the newest version of 1.20.1. It appears that the interface isn't transparent as shown in the pictures of your gallery, but that it shows the typical dirt background of the normal minecraft menu interface. I'll provide a picture below to show what I mean.
_(Player name and skin were blurred for privacy reasons.)_

![2024-12-04_22 30 06](https://github.com/user-attachments/assets/cb5c5db2-9a32-423b-ac98-ab7fb8586ea2)

This could be intentional though on your end, I'm not sure.
In any case, thank you for your help!

This was tested on a minimal instance, so it's not a conflict with another mod.

**Comment by orifu** [comment]
minecraft 1.20.5 added the transparent/blurred ui, so on versions before that it'll have the non-transparent look. i do agree that having half the screen be transparent and half opaque doesn't look great, so maybe it should be fully opaque (matching the resource pack screen?)

**Comment by avilonlegends** [comment]
That might be better, yes, if it's not too much of a hassle for you?

And thank you so much for your quick response!

**Comment by orifu** [comment]
i've added the dirt background to all screens, which will be in the next update
