### ISSUE TITLE
entity culling incompatibility

### ISSUE THREAD

**Issue by oJamez** [rosebudmods/skin-overrides#8]
### minecraft version

The Garden Awakens (1.21.4)

### mod version

2.2.2

### mod loader

fabric

### what went wrong?

I've been trying to run mc on my school pc for the past hour the game works perfect until I try using this mod. When I override a skin using an account username it overrides it but when I join into a singleplayer world it just immediately crashes upon joining, when I remove the mod then the game works just fine
![image](https://github.com/user-attachments/assets/b3a023ba-e956-46fb-b9bb-0d32492f2f04)
this is the image of mods that I am running the game with, if it is useful by any means

### log file

https://mclo.gs/RXIlhhV

**Comment by orifu** [comment]
thanks for the report! i will look into this more later, but for now do you have any broken images in the `skin_overrides` or `cape_overrides` folders in `.minecraft`?

**Comment by orifu** [comment]
okay, i'll try to reproduce this later today!

**Comment by orifu** [comment]
sorry for the delay! i've found out it's an incompatibility with entity culling, so i'll work on a fix for that

**Comment by orifu** [comment]
issue will be fixed in the next update (f6dfd3239b3a999775527fb8f0af0cdf9f157e92)

**Comment by 3throw** [comment]
Worked like magic. Thank you!
