### ISSUE TITLE
Game freezes when changing skin override

### ISSUE THREAD

**Issue by 3throw** [rosebudmods/skin-overrides#9]
### minecraft version

The Garden Awakens (1.21.4)

### mod version

2.2.2

### mod loader

fabric

### what went wrong?

I go to change my skin on 1.21.4, and my game crashes if I'm in a preloaded world. If I change my skin override before loading into a new world, my game freezes on "Generating Terrain" or "Loading World". If I change my skin override then load into a preloaded world, my game also freezes.

**Comment by orifu** [comment]
thanks for reporting! can you post a log so i have more information?

**Comment by orifu** [comment]
this is a problem that happens with entityculling (#8). you can remove the mod or wait for the next update which fixes it

**Comment by 3throw** [comment]
I'll try it, thanks!
